Salesforce Template Application/force-app/main/default/objects/TriggerSettings__mdt/TriggerSettings__mdt.object-meta.xml
<CustomObject>
    <description>Trigger Settings for Application</description>
    <label>Trigger Setting</label>
    <pluralLabel>Trigger Settings</pluralLabel>
</CustomObject>

Salesforce Template Application/force-app/main/default/objects/TriggerSettings__mdt/fields/isActive__c.field-meta.xml
<CustomField>
    <fullName>isActive__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Is Trigger is Activ and called when required</description>
    <inlineHelpText>Is Trigger is Activ and called when required</inlineHelpText>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

Salesforce Template Application/force-app/main/default/classes/TriggerSetting.cls
/**
 * @description       : 
 * @author            : Yogesh.Bhosale
 * @group             : 
 * @last modified on  : 12-11-2021
 * @last modified by  : Yogesh.Bhosale
**/
public with sharing class TriggerSetting {

    /**
     * 
     */
    public static Boolean isTriggerActive( String triggerClassName ){
        Boolean isTriggerActive = true;
        TriggerSettings__mdt setting = TriggerSettings__mdt.getInstance(triggerClassName); 
        
            if( setting != null ){
                isTriggerActive = setting.isActive__c;
            }
            
        return isTriggerActive;
    }

}